name: 'Upload coverage to codecov'
description: 'Uploads coverage to codecov with retries'
inputs:
  files:
    description: 'Coverage files to upload'
    required: true
  flags:
    description: 'Flags for codecov'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Retry upload
      uses: Wandalen/wretry.action@v3.5.0
      with:
        attempt_limit: 6
        # sleep 10 seconds between retries
        attempt_delay: 10000
        action: codecov/codecov-action@v4.0.1
        with: |
          files: ${{ inputs.files }}
          flags: ${{ inputs.flags }}
          verbose: true
          fail_ci_if_error: true
          token: 1c38098f-49c7-452a-bda1-45955bed45de
