name: Test and Build binaries

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-go
      - run: go version
        # download dependencies separately to keep unit test step's output cleaner
      - name: go mod download
        run: go mod download
      - name: Run test
        run: make test
      - name: Run coverage
        run: make cover