name: Test and Build binaries

on:
  push:

permissions:
  contents: read

jobs:
  unit-test:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit
      - uses: actions/checkout
      - uses: actions/setup-go
      - run: go version
      - name: go mod download
        run: go mod download
      - name: Run test
        run: make test-ci